config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#index"

  resources :products do
    resources :reviews, except: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :title, :description, :price, :presence => true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  before_action :set_product, only: [:edit, :update, :show, :destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
    if user_signed_in?
      if !current_user.admin?
        flash[:warning] = 'You must have administrator privileges to see that page'
        redirect_to root_path
      end
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product Successfully Saved"
      redirect_to product_path(@product)
    else
      flash[:warning] = "Product Not Saved"
      render :new
    end
  end

  def edit
    if user_signed_in?
      if !current_user.admin?
        flash[:warning] = 'You must have administrator privileges to see that page'
        redirect_to root_path
      end
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product Successfully Edited"
      redirect_to product_path(@product)
    else
      flash[:warning] = "Product Not Updated"
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product Deleted"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :description, :price, :image)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else
      flash[:warning] = 'Review Not Saved'
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @user = User.find(@review.user_id)
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @user = User.find(@review.user_id)
    if @review.update(review_params)
      flash[:success] = 'Review Successfully Updated'
      redirect_to product_path(@product)
    else
      flash[:warning] = 'Review Not Updated'
      redirect_to product_path(@product)
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = 'Successfully Deleted Review'
    redirect_to product_path(@product)
  end

  private
  def review_params
    params.require(:review).permit(:content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if flash[:success] %>
  <div class="success bg-success">Flash: <%= flash[:success] %></div>
<% end %>

<% if flash[:warning] %>
  <div class="warning bg-danger">Flash: <%= flash[:warning] %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Bon Appetizers', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <% if current_user.admin? %>
          <li><%= link_to 'Add a Product', new_product_path %></li>
          <% end %>
        <% end %>
        <li><%= link_to 'Our Products', products_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a>Logged in as <strong><%= current_user.email %></strong>.</a></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BonAppetizers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1 class="text-center">Welcome to Bon Appetizers!</h1>
<br>
<br>


<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/products/_form.html.erb
<%= render 'layouts/errors', object: @product %>
<%= form_for(@product, multipart: true) do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= f.label :price %>
    <%= f.number_field :price, :step => "0.01", class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit and Upload', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<% if @products.any? %>
  <h1 class='text-center'>What we offer.</h1>
  <div class="row">
  <% @products.each do |product| %>
      <div class="col-md-4">
        <%= image_tag product.image, class: 'center-block' %>
        <br>
        <p class="text-center">
          <%= link_to product.title, product_path(product) %>
        </p>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <p class="text-center">
              <%= link_to 'Edit Product Listing', edit_product_path(product), class: 'btn btn-xs btn-warning' %>
            </p>
            <p class="text-center">
              <%= link_to 'Delete Product Listing', product_path(product), method: :delete, data: {confirm: 'Confirm Deletion?'}, class: 'btn btn-xs btn-danger' %>
            </p>
          <% end %>
        <% end %>
        <p class="text-center">
          $<%= product.price %>
        </p>
        <p class="text-center">
          <%= truncate(product.description, length: 25) %>
        </p>
      </div>
  <% end %>
</div>
<% else %>
  <p>
    No products to display. Check back later.
  </p>
<% end %>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="text-center"><%= @product.title %></h1>

<%= image_tag @product.image, class: 'center-block' %>
<br>
<p class="text-center">
  $<%= @product.price %>
</p>
<p class="text-center">
  <%= @product.description %>
</p>
<hr>
<% if user_signed_in? %>
<%= render 'reviews/form' %>
<hr>
<% end %>
<% if @product.reviews.any? %>
  <% @product.reviews.each do |review| %>
  <p class="text-center">
    <%= User.find(review.user_id).email %> writes:
  </p>
  <p class="text-center">
    <%= review.content %>
  </p>
  <% if current_user %>
    <% if current_user.id == review.user_id || current_user.admin? %>
      <%= link_to 'Manage Review', edit_product_review_path(@product, review), class: 'btn btn-xs btn-warning' %>
    <% end %>
  <% end %>
  <hr>
  <% end %>
<% else %>
<p class="text-center">
  There are no reviews on this product yet.
</p>
<% end %>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', object: @review %>
<%= form_for [@product, @review] do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %><br>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form' %>
<br>
<%= link_to 'Delete Review', product_review_path(@product, @review), method: :delete, class: 'btn btn-danger' %>

app/views/reviews/new.html.erb
<%= render 'layouts/errors', object: @review %>

<%= link_to 'Back to Product', product_path(@product) %>